<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Abhilash" name="Edit Damage Model Add Graph With InValid Data" tests="1" failures="1" timestamp="16 Sep 2015 09:42:40 GMT" time="45.83" errors="0">
  <testcase name="EditDamageModelAddGraphWithInValidData" time="28.918" classname="com.eigenRisk.TestSuite.Damage_ModelManager">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 3, Size: 3">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.eigenRisk.functionalities.DamageModelManager.findDamageModel(DamageModelManager.java:971)
	at com.eigenRisk.functionalities.DamageModelManager.editDamageModelGraph(DamageModelManager.java:743)
	at com.eigenRisk.functionalities.DamageModelManager.editDamageModelGraphInValidData(DamageModelManager.java:630)
	at com.eigenRisk.TestSuite.Damage_ModelManager.EditDamageModelAddGraphWithInValidData(Damage_ModelManager.java:294)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- EditDamageModelAddGraphWithInValidData -->
</testsuite> <!-- Edit Damage Model Add Graph With InValid Data -->
