<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Abhilash" name="Add Damage Function One" tests="1" failures="1" timestamp="16 Sep 2015 09:40:21 GMT" time="57.314" errors="0">
  <testcase name="AddDamageFunctionOne" time="28.919" classname="com.eigenRisk.TestSuite.Damage_ModelManager">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 3, Size: 3">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.eigenRisk.functionalities.DamageModelManager.findDamageModel(DamageModelManager.java:971)
	at com.eigenRisk.functionalities.DamageModelManager.addDamageFunction(DamageModelManager.java:280)
	at com.eigenRisk.TestSuite.Damage_ModelManager.AddDamageFunctionOne(Damage_ModelManager.java:235)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- AddDamageFunctionOne -->
</testsuite> <!-- Add Damage Function One -->
