<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Abhilash" name="Edit Damage Model Add Graph With Valid Data" tests="1" failures="1" timestamp="16 Sep 2015 09:41:54 GMT" time="46.998" errors="0">
  <testcase name="EditDamageModelAddGraphWithValidData" time="29.963" classname="com.eigenRisk.TestSuite.Damage_ModelManager">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 3, Size: 3">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.eigenRisk.functionalities.DamageModelManager.findDamageModel(DamageModelManager.java:971)
	at com.eigenRisk.functionalities.DamageModelManager.editDamageModelGraph(DamageModelManager.java:743)
	at com.eigenRisk.functionalities.DamageModelManager.editDamageModelGraphValidData(DamageModelManager.java:398)
	at com.eigenRisk.TestSuite.Damage_ModelManager.EditDamageModelAddGraphWithValidData(Damage_ModelManager.java:275)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- EditDamageModelAddGraphWithValidData -->
</testsuite> <!-- Edit Damage Model Add Graph With Valid Data -->
